name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'mix.exs'
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    name: Release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build for production
        run: LFM_TOKEN=${{ secrets.LFM_TOKEN }} PORT=3000 make release
      - name: Run release
        run: make run
