name: Tests

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  mix-tests:
    name: Mix tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: 24.0
          elixir-version: 1.13.0
      - name: Install Dependencies
        run: mix deps.get --only test --verbose
      - name: Install Hex & Rebar3
        run: |
          mix local.hex --force --if-needed
          mix local.rebar --force --if-needed
      - name: Run unit tests
        run: LFM_TOKEN=${{ secrets.LFM_TOKEN }} MIX_ENV=test make test
